const CATEGORIES = [
  "\uAC04\uD3B8\uC2DD",
  "\uBCA0\uC774\uCEE4\uB9AC",
  "\uC2E0\uC120\uC2DD\uD488",
  "\uBC18\uCC2C",
];
const SESSION_COOKIE = "shop_session";
const SHIPPING_THRESHOLD = 30000;
const SHIPPING_FEE = 3000;

export default { async fetch(request, env) { const url = new URL(request.url); try { return url.pathname.startsWith("/api/") ? await handleApi(request, env, url) : env.ASSETS.fetch(request); } catch (error) { console.error(error); return json({ error: "???됰Ŋ?????꿔꺂??節뉖き???? ?꿔꺂??쭫?묒쒜?壤??????" }, 500); } } };

async function handleApi(request, env, url) {
  const method = request.method; const productMatch = url.pathname.match(/^\/api\/products\/(\d+)$/); const cartItemMatch = url.pathname.match(/^\/api\/cart\/(\d+)$/); const orderMatch = url.pathname.match(/^\/api\/orders\/([0-9a-f-]+)$/i);
  if (method === "GET" && url.pathname === "/api/categories") { const { results } = await env.DB.prepare("SELECT c.name AS category, COUNT(p.id) AS count FROM categories c LEFT JOIN products p ON p.category_id = c.id AND p.is_active = 1 WHERE c.is_active = 1 GROUP BY c.id, c.name ORDER BY c.sort_order").all(); return json({ categories: CATEGORIES.map((name) => ({ name, count: results.find((x) => x.category === name)?.count || 0 })) }); }
  if (method === "GET" && url.pathname === "/api/products") { const category = url.searchParams.get("category") || ""; const query = (url.searchParams.get("query") || "").trim().slice(0, 80); const sort = url.searchParams.get("sort") || "recommended"; if (category && !CATEGORIES.includes(category)) return json({ error: "????ъ군???? ??? ??⑤㈇???亦껋꼨????쒙쭫??????뉖뤁??" }, 400); const order = { recommended: "sales_rank ASC, id ASC", new: "is_new DESC, id DESC", sales: "sales_rank ASC, id ASC", price: "sale_price ASC, id ASC" }[sort] || "sales_rank ASC, id ASC"; const clauses = ["p.is_active = 1"]; const binds = []; if (category) { clauses.push("c.name = ?"); binds.push(category); } if (query) { clauses.push("(name LIKE ? OR short_description LIKE ? OR description LIKE ?)"); binds.push(`%${query}%`, `%${query}%`, `%${query}%`); } const { results } = await env.DB.prepare(`SELECT p.*, c.name AS category_name FROM products p LEFT JOIN categories c ON c.id = p.category_id WHERE ${clauses.join(" AND ")} ORDER BY ${order}`).bind(...binds).all(); return json({ products: results, count: results.length }); }
  if (method === "GET" && productMatch) { const product = await env.DB.prepare("SELECT * FROM products WHERE id = ? AND is_active = 1").bind(Number(productMatch[1])).first(); return product ? json({ product }) : json({ error: "????브컯????꿔꺂????????????ㅿ폍??????딅젩." }, 404); }
  if (!url.pathname.startsWith("/api/cart") && !url.pathname.startsWith("/api/orders")) return json({ error: "???됰Ŋ????嚥▲굧???뚪뜮?熬곣벀嫄??꿔꺂????????????ㅿ폍??????딅젩." }, 404);
  const session = await ensureSession(request, env); const headers = session.created ? { "Set-Cookie": makeSessionCookie(session.id, url) } : {};
  if (method === "GET" && url.pathname === "/api/cart") return json(await readCart(env, session.id), 200, headers);
  if (method === "POST" && url.pathname === "/api/cart") { const body = await readJson(request); const productId = toPositiveInteger(body.productId); const qty = toQuantity(body.qty); if (!productId || !qty) return json({ error: "????브컯???????????癲ル슢캉????????녿뮝???ル튉??" }, 400, headers); const product = await env.DB.prepare("SELECT id FROM products WHERE id = ? AND is_active = 1").bind(productId).first(); if (!product) return json({ error: "????브컯????꿔꺂????????????ㅿ폍??????딅젩." }, 404, headers); await env.DB.prepare(`INSERT INTO cart_items (session_id, product_id, qty) VALUES (?, ?, ?) ON CONFLICT(session_id, product_id) DO UPDATE SET qty = MIN(99, cart_items.qty + excluded.qty)`).bind(session.id, productId, qty).run(); return json(await readCart(env, session.id), 200, headers); }
  if (method === "PATCH" && cartItemMatch) { const qty = toQuantity((await readJson(request)).qty); if (!qty) return json({ error: "??????? 1~99??醫딆┻???????딅젩." }, 400, headers); const result = await env.DB.prepare("UPDATE cart_items SET qty = ? WHERE id = ? AND session_id = ?").bind(qty, Number(cartItemMatch[1]), session.id).run(); return result.meta.changes ? json(await readCart(env, session.id), 200, headers) : json({ error: "?逆곷틳源??嶺?????????꿔꺂????????????ㅿ폍??????딅젩." }, 404, headers); }
  if (method === "DELETE" && cartItemMatch) { const result = await env.DB.prepare("DELETE FROM cart_items WHERE id = ? AND session_id = ?").bind(Number(cartItemMatch[1]), session.id).run(); return result.meta.changes ? json(await readCart(env, session.id), 200, headers) : json({ error: "?逆곷틳源??嶺?????????꿔꺂????????????ㅿ폍??????딅젩." }, 404, headers); }
  if (method === "POST" && url.pathname === "/api/orders") { const body = await readJson(request); const selected = Array.isArray(body.itemIds) && body.itemIds.length ? body.itemIds.map(Number).filter(Number.isInteger) : null; const cart = await readCart(env, session.id, selected); if (!cart.items.length) return json({ error: "????ｋ????逆곷틳源??嶺???????브컯???????ㅿ폍??????딅젩." }, 400, headers); const orderId = crypto.randomUUID(); const statements = [env.DB.prepare("INSERT INTO orders (id, session_id, subtotal, discount_total, shipping_fee, total, status) VALUES (?, ?, ?, ?, ?, ?, 'pending')").bind(orderId, session.id, cart.subtotal, cart.discountTotal, cart.shippingFee, cart.total), ...cart.items.map((item) => env.DB.prepare("INSERT INTO order_items (order_id, product_id, product_name, qty, price, original_price) VALUES (?, ?, ?, ?, ?, ?)").bind(orderId, item.product_id, item.name || "?癒?꼻 ?ル굝利??怨밸?", item.qty, item.sale_price, item.original_price)), env.DB.prepare(`DELETE FROM cart_items WHERE session_id = ?${selected ? ` AND id IN (${selected.map(() => "?").join(",")})` : ""}`).bind(session.id, ...(selected || []))]; await env.DB.batch(statements); return json({ orderId }, 201, headers); }
  if (method === "GET" && orderMatch) { const order = await env.DB.prepare("SELECT * FROM orders WHERE id = ? AND session_id = ?").bind(orderMatch[1], session.id).first(); if (!order) return json({ error: "???녿뮝?筌믡굥利???꿔꺂????????????ㅿ폍??????딅젩." }, 404, headers); const { results: items } = await env.DB.prepare("SELECT oi.product_id, oi.product_name, oi.qty, oi.price, oi.original_price, COALESCE(p.name, '?????????띻샴癲?????브컯?') AS name, COALESCE(p.image_url, '') AS image_url FROM order_items oi LEFT JOIN products p ON p.id = oi.product_id WHERE oi.order_id = ? ORDER BY oi.id").bind(order.id).all(); return json({ order: { ...order, items } }, 200, headers); }
  return json({ error: "???됰Ŋ????嚥▲굧???뚪뜮?熬곣벀嫄??꿔꺂????????????ㅿ폍??????딅젩." }, 404, headers);
}
async function ensureSession(request, env) { const candidate = parseCookies(request.headers.get("Cookie") || "")[SESSION_COOKIE]; const valid = candidate && /^[0-9a-f-]{36}$/i.test(candidate); const id = valid ? candidate : crypto.randomUUID(); const existing = valid ? await env.DB.prepare("SELECT id FROM guest_sessions WHERE id = ?").bind(id).first() : null; if (!existing) await env.DB.prepare("INSERT OR IGNORE INTO guest_sessions (id) VALUES (?)").bind(id).run(); return { id, created: !existing }; }
async function readCart(env, sessionId, selectedIds = null) { const where = ["ci.session_id = ?"]; const binds = [sessionId]; if (selectedIds) { if (!selectedIds.length) return emptyCart(); where.push(`ci.id IN (${selectedIds.map(() => "?").join(",")})`); binds.push(...selectedIds); } const { results: items } = await env.DB.prepare(`SELECT ci.id, ci.product_id, ci.qty, p.name, p.image_url, p.original_price, p.sale_price, p.discount_rate, p.coupon_label, CASE WHEN p.id IS NULL OR p.is_active = 0 THEN 1 ELSE 0 END AS unavailable FROM cart_items ci LEFT JOIN products p ON p.id = ci.product_id WHERE ${where.join(" AND ")} ORDER BY ci.id`).bind(...binds).all(); const available = items.filter(x => !x.unavailable); const originalSubtotal = available.reduce((s, x) => s + x.original_price * x.qty, 0); const subtotal = available.reduce((s, x) => s + x.sale_price * x.qty, 0); const discountTotal = originalSubtotal - subtotal; const shippingFee = subtotal && subtotal < SHIPPING_THRESHOLD ? SHIPPING_FEE : 0; return { items, itemCount: items.reduce((s, x) => s + x.qty, 0), originalSubtotal, subtotal, discountTotal, shippingFee, total: subtotal + shippingFee }; }
function emptyCart() { return { items: [], itemCount: 0, originalSubtotal: 0, subtotal: 0, discountTotal: 0, shippingFee: 0, total: 0 }; }
function parseCookies(header) { return Object.fromEntries(header.split(";").map((x) => x.trim()).filter(Boolean).map((x) => { const i = x.indexOf("="); return [x.slice(0, i), decodeURIComponent(x.slice(i + 1))]; })); }
function makeSessionCookie(id, url) { return `${SESSION_COOKIE}=${encodeURIComponent(id)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${url.protocol === "https:" ? "; Secure" : ""}`; }
async function readJson(request) { try { return await request.json(); } catch { return {}; } }
function toPositiveInteger(v) { const n = Number(v); return Number.isInteger(n) && n > 0 ? n : null; }
function toQuantity(v) { const n = Number(v); return Number.isInteger(n) && n >= 1 && n <= 99 ? n : null; }
function json(data, status = 200, extra = {}) { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json; charset=utf-8", ...extra } }); }










